root: true
env:
  node: true
  es6: true # Enable ES6 syntax support
extends:
  - eslint:recommended
  - plugin:mocha/recommended

parserOptions:
  ecmaVersion: 2021 # Specify the ECMAScript version
  sourceType: module # Specify the source type (e.g., module or script)

rules:
  indent:
    - error
    - 2
